### ISSUE TITLE
갑자기 make 에러 뜨는데요?

### ISSUE THREAD

**Issue by moeboard** [MicroBitcoinOrg/MicroBitcoin#1]
CXX      libbitcoin_common_a-chainparams.o
  CXX      libbitcoin_common_a-coins.o
chainparams.cpp: In constructor ‘CMainParams::CMainParams()’:
chainparams.cpp:117:19: error: ‘struct Consensus::Params’ has no member named ‘replyFixHeight’
         consensus.replyFixHeight = 999999999;
                   ^
chainparams.cpp: In constructor ‘CTestNetParams::CTestNetParams()’:
chainparams.cpp:244:19: error: ‘struct Consensus::Params’ has no member named ‘replyFixHeight’
         consensus.replyFixHeight = 999999999;
                   ^
chainparams.cpp: In constructor ‘CRegTestParams::CRegTestParams()’:
chainparams.cpp:340:19: error: ‘struct Consensus::Params’ has no member named ‘replyFixHeight’
         consensus.replyFixHeight = 999999999;
                   ^
Makefile:5064: recipe for target 'libbitcoin_common_a-chainparams.o' failed
make[2]: *** [libbitcoin_common_a-chainparams.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: Leaving directory '/root/MicroBitcoin/src'
Makefile:9347: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/root/MicroBitcoin/src'
Makefile:747: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1

**Comment by itwysgsl** [comment]
This [commit](https://github.com/MicroBitcoinOrg/MicroBitcoin/commit/eacf82421dd138ba95e12c320254a0f2bc30fa2a) should fix it.

**Comment by moeboard** [comment]
Thank you.
I downloaded the release version.
And it is compiling.
Well done.
