### ISSUE TITLE
wrong dounload or something

### ISSUE THREAD

**Issue by coltmerg420** [MicroBitcoinOrg/MicroBitcoin#16]
I downloaded this MicroBitcoin_Qt_0.16.5_Windows.zip  https://github.com/MicroBitcoinOrg/MicroBitcoin/releases/tag/0.16.5
 after unpack and install i got this MicroBitcoin:0.16.4  v0.16.4.0-dfcf777-dirty no seeds or nods or connections.

**Comment by itwysgsl** [comment]
Hmm, let me check it

**Comment by itwysgsl** [comment]
Updated release available [here](https://github.com/MicroBitcoinOrg/MicroBitcoin/releases/tag/0.16.5).
