### ISSUE TITLE
MBC Wallet Security

### ISSUE THREAD

**Issue by mesterica** [MicroBitcoinOrg/MicroBitcoin#23]
Hi and sorry for my english, I use Micro-Qt 3.0 wallet on windows and I have this question (proposal):

> Why the wallet never ask for the password after closing and reopen? (I have a encrypted wallet ) Imagine if someone stoling or have acces on  PC.

Thank you

**Comment by placeprintcorp** [comment]
Your query has been received.

Personally I have only used the web wallet, and it does reset. Perhaps try
using the web wallet on local host, and it will accomplish all the goals
you have of resetting password, and changing wallet per each login.

Hope this helps.
